apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-server-deployment
  labels:
    app: postgres-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-server
  template:
    metadata:
      labels:
        app: postgres-server
    spec:
      containers:
        - name: postgresql
          image: postgres
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: fast
            - name: POSTGRES_DB
              value: poll
            - name: POSTGRES_PASSWORD
              value: 1234qwer
