FROM python:3.8-slim-buster

RUN apt update \
    && apt install -y gcc libpq-dev python-dev \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /usr/src/app
COPY . .
RUN pip install -r requirements.txt

EXPOSE 8000
ENTRYPOINT ["sh", "./docker-entrypoint.sh"]