apiVersion: v1
kind: Service
metadata:
  name: backend-server-service
spec:
  clusterIP: None
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
      name: server-port
  selector:
    app: backend-server