apiVersion: v1
kind: Service
metadata:
  name: frontend-server-service
spec:
  #clusterIP: None
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: server-port
  selector:
    app: frontend-server
  type: LoadBalancer