apiVersion: v1
kind: Service
metadata:
  name: postgres-server-service
spec:
  clusterIP: None
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
      name: db-port
  selector:
    app: postgres-server
